# Import Data

In [4]:
from pmdarima import auto_arima
print("✅ pmdarima ready to use!")

ModuleNotFoundError: No module named 'pmdarima'

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

import plotly.graph_objects as go
import plotly.express as px

In [7]:
pd.set_option('display.max_columns', None)

In [9]:
bsm_all = pd.read_excel('data/bsm_all.xlsx').drop(columns = ['KETBPB'])
bsm_all.head()

,NO_BSM,NAMA_BARANG,JUMLAH,JMLDISETUJUI,HRGSATUAN,TOTAL,STATUS,BSM_CREATED_ON,NO_BPB,KODEBARANG,KODELOKASI,JENISSTOK,NOLOKB,USERIDAPP,DATEAPP,BSM_CLOSED_BY,BSM_CLOSED_ON,LOKASIBUAT,KODEKAPAL,KODEALATBERAT,NAMAOBJEK,KODEAKUNBRG,KODEAKUNBSM
0,BSM/004558/03/23,"P553000/ J86-19009 LUBE FILTER,SPIN-ON FULL FL...",2.0,2.0,334374.47,668748.94,CLOSE,18/03/2023,BPB/000327/UMU/03/23,FLTRJB619009,KLNK,JADI,NaN,novi_h,2023-03-30 08:37:53,msafi,2023-04-05 19:22:25,KLNK,NaN,NaN,NaN,6XX.02.02.01,NaN
1,BSM/004558/03/23,"FF-232/ P55-7440 FUEL FILTER,SPIN-ON SECONDARY...",6.0,6.0,62328.25,373969.50,CLOSE,18/03/2023,BPB/000327/UMU/03/23,FLTRFF-232/P55,KLNK,JADI,NaN,novi_h,2023-03-30 08:37:53,msafi,2023-04-05 19:22:25,KLNK,NaN,NaN,NaN,6XX.02.02.01,NaN
2,BSM/004558/03/23,FILTER RACOR FH 1000,2.0,2.0,749600.00,1499200.00,CLOSE,18/03/2023,BPB/000327/UMU/03/23,FLTRRACORFH1000,KLNK,JADI,NaN,novi_h,2023-03-30 08:37:53,msafi,2023-04-05 19:22:25,KLNK,NaN,NaN,NaN,3XX.01.02,NaN
3,BSM/004555/03/23,ORING 30,3.0,3.0,30000.00,90000.00,CLOSE,18/03/2023,BPB/000033/MR/03/23,ORING30.,KLNK,JADI,LOKB/0139/MR/02/23,avian,2023-03-18 10:29:15,avian,2023-03-18 10:29:15,KLNK,KAA,NaN,KAPPA (KAA),6XX.02.02.01,NaN
4,BSM/004555/03/23,ORING G 80 VITON,3.0,3.0,16999.81,50999.43,CLOSE,18/03/2023,BPB/000033/MR/03/23,ORINGG800V,KLNK,JADI,LOKB/0139/MR/02/23,avian,2023-03-18 10:29:15,avian,2023-03-18 10:29:15,KLNK,KAA,NaN,KAPPA (KAA),6XX.02.02.01,NaN